### PR TITLE
Create a Community Code of Conduct

### PR DESCRIPTION
**Pull request by mike-matera**
This PR introduces a code of conduct document. Every contributor from now into the future should read and understand this document and act accordingly.

### CODE REVIEW

**Comment by OrionOth** [comment]
I have to say, I really like the language used in the document, its intentions, its structural clarity, as well as what it will do for us.

Personally, I don't work well with just this half of things, and I'd also like to see an accompanying `CONTRIBUTING.md` to help clarify what to do, rather than what not do. As we've talked earlier in the year about making things too complex leading to a higher entry barrier, I don't think those contribution guidelines should be super strict.

For these contribution guidelines, I propose:
- PRs start in Draft until committer thinks it's ready for merge
- Before marking a PR as ready for review, committer rebases history to squash changes into more concise, atomic commits (optional, if this is not done then the entire PR should be merged as a single squash commit)
- Once there is a review on a PR, history rewrites don't happen
- A given review is invalidated if there is a commit after it making a change not discussed in that review
- There must be at least 1/2 current, approving reviews to merge
- ...

Those may seem strict, but they are rather straightforward and mechanical, and mostly just affect reviewers.

Thoughts?

**Comment by mike-matera** [comment]
This is a perfect example of a totally negative comment disguised as a high minded debate about the "right" thing to do. Let me read the comment back to you:

1. It's better to do nothing.  (*It's incomplete without..."*)
2. I'm an expert, you're not. ("*The way it proceeded was... abnormal compared to many open source projects' ...*) 
3. My feelings matter, yours don't. (*"feels like this is only half a solution," "I felt it was too fast,"*)
4. Terrible things will happen if you don't listen to me. (*"... and it will collapse on us all."*)

You can't bully me because I know I belong. But, your irrational and unrelenting hostility to everyone else's code has made this an unsafe space for coders and has left me asking whether we really need you on this project.

**Comment by OrionOth** [comment]
I'm... not trying to bully anyone, or be hostile, I want to be as friendly as possible. 

I have a hard time working with stuff like this, without anything on the other side.

I meant absolutely nothing in my comment, nor this one, in any sort of emotional/tonal light.

(1) Its not better to do nothing. I want this to be added, merged, as-is. I just need more to make proper use of it.

(4) I was trying to make a logical analogy, not allude to anything.

I'll rephrase the entire thing. Thank you for your advice.

Edit: This is done. If you want to see the original version of the comment, GitHub lets you do that by clicking the edit timestamp.

**Comment by mike-matera** [comment]
I like the idea of having a `CONTRIBUTING.md`. Are there examples of ones you like in other open source projects? Maybe we could steal one and make edits to meet our needs (or take it wholesale). 

*The revised comment is really good. I love how you framed it as what to do versus what not to do. It made the idea that you need both really clear. Thank you for the revisions.*

**Review by steph-lheureux — APPROVED** [review]
This document is an important addition which will aid in sustaining a positive community within Cabrillo Robotics Club. I really like the language used and the standards set for members and community leaders to uphold. While this document likely rose out of the situation surrounding PR #188  , its scope and importance in the club is not limited to this situation. Having this document will help to ensure our community remains supportive and welcoming and provides specific guidelines and consequences regarding members actions. 
I suggest that once merged, this document should be linked it in the `#welcome` channel on discord.

**Comment by steph-lheureux** [comment]
I also like the idea of having a `CONTRIBUTING.md`, it is important to provide guidelines on how things should be done. However the current lack there of should not delay something which is ready to merge, in my opinion.
I suggest when things like this arise, when there is a PR which accomplishes what describes it does (in this case, creates a Code of Conduct), but there may be something related that is missing (a standard for contributing), create an issue. There is no reason to delay working code from being merged. But these related changes of course need to happen, so I believe creating an issue is a good solution.

In addition to a `CONTRIBUTING.md` lets add a `PR_REVIEW.md`.
There's a section in [The Missing README](https://themissingreadme.com/) surrounding code review. It has some good suggestions about reviewing code and having code reviewed. I think we should consider adding excerpts and/or ideas from the book to these documents.
But again these are ideas for a future PR, the current PR should be merged

**Review by akcarney — APPROVED** [review]
I found these guidelines to be very logical and straightforward. I agree that the observance of these standards would aid the club in upholding an accessible and collaborative environment.

**Review by tinymassi — APPROVED** [review]
This document is an excellent addition to the infrastructure and behavior of this team. After having read the document, I'm glad something like this was added.

**Pull request merged**
